### ISSUE TITLE
More placeholders for commit messages

### ISSUE THREAD

**Issue by tgerulaitis** [meanbee/magerun-dac#1]
Currently, when supplying a custom commit messages with --commit-message, you can add a %s in the commit message in place of the resulting file that's being committed. This works simply because the message is passed through sprintf() before being used.

It would be more useful to have a proper placeholder system and allow for more placeholders such as the source and destination themes to be used in custom commit messages.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
